name: Build and Test

on: 
  workflow_dispatch:
  push:
    paths:
      - "src/Transmitly.TemplateEngine.Scriban/**"
jobs:
  build_test_deploy_template_engine:
    uses: transmitly/transmitly/.github/workflows/build-and-deploy-template-engine.yml@main
    with: 
      templateEngineName: Transmitly.TemplateEngine.Scriban
    secrets: inherit
